---
provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5
    driver:
      name: vagrant
    driver_config:
      require_chef_omnibus: 11.12.4
      network:
      - ["private_network", {ip: "192.168.33.14"}]
      - ["forwarded_port", {guest: 3000, host: 8004, auto_correct: true}]

suites:
  - name: mysql
    run_list:
      - recipe[yum::default]
      - recipe[yum-epel::default]
      - recipe[networking_basic::default]
      - recipe[mysql::server]
      - recipe[mysql-custom::default]
      - recipe[redmine2::default]
    attributes:
      mysql:
        server_root_password: 'secretpassword'
      redmine: 
        version: '2.5.1'
        host: 'localhost'
        db: 
          type: 'mysql'

  - name: postgresql 
    run_list:
      - recipe[yum::default]
      - recipe[yum-epel::default]
      - recipe[networking_basic::default]
      - recipe[postgresql::server]
      - recipe[redmine2::default]
    attributes:
      postgresql:
        password:
          postgres: "secretpassword"
      redmine: 
        version: '2.5.1'
        host: 'localhost'
        db: 
          type: 'postgresql'
