---
driver:
  name: vagrant
  driver_config:
    require_chef_omnibus: 11.12.4

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5
    driver_config:
      network:
      - ["forwarded_port", {guest: 3000, host: 3000}]
      - ["private_network", {ip: "192.168.33.1"}]

suites:
  - name: default
    run_list:
      - recipe[yum]
      - recipe[yum-epel]
      - recipe[networking_basic]
      - recipe[mysql::server]
      - recipe[redmine2]
    attributes:
      mysql:
        server_root_password: 'secretpassword'
        server_repl_password: 'secretpassword'
        server_debian_password: 'secretpassword'
      redmine: 
        version: '2.5.1'
        host: 'localhost'
        db: 
          type: 'mysql'

  - name: postgresql 
    run_list:
      - recipe[yum]
      - recipe[yum-epel]
      - recipe[networking_basic]
      - recipe[postgresql::server]
      - recipe[redmine2]
    attributes:
      postgresql:
        password:
          postgres: "secretpassword"
      redmine: 
        version: '2.5.1'
        host: 'localhost'
        db: 
          type: 'postgresql'
