---
provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-13.10
    driver:
      name: vagrant
    driver_config:
      network:
      - ["forwarded_port", {guest: 80, host: 8888}]
      - ["private_network", {ip: "192.168.33.30"}]
      require_chef_omnibus: 11.12.4

  - name: centos-6.5
    driver:
      name: vagrant
    driver_config:
      require_chef_omnibus: 11.12.4
      network:
      - ["forwarded_port", {guest: 80, host: 8088}]
      - ["private_network", {ip: "192.168.33.40"}]

suites:
  - name: mysql
    run_list:
      - recipe[yum-epel]
      - recipe[apache2::default]
      - recipe[mysql::server]
      - recipe[mysql::client]
      - recipe[mysql-custom::default]
      - recipe[zabbix]
      - recipe[zabbix::database]
      - recipe[zabbix::server]
      - recipe[zabbix::web]
      - recipe[zabbix-custom::japanese_font]
    attributes:
      zabbix:
        server:
          version: 2.2.1
        agent:
          servers: ['localhost']
          version: 2.2.1
        web:
          fqdn: 'localhost'
      mysql:
        server_root_password: nil
