---
provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5
    driver:
      name: vagrant
    driver_config:
      require_chef_omnibus: 11.12.4
      network:
      - ["private_network", {ip: "192.168.33.20"}]
      - ["forwarded_port", {guest: 80, host: 8007, auto_correct: true}]

  - name: ubuntu-13.10
    driver:
      name: vagrant
    driver_config:
      network:
      - ["private_network", {ip: "192.168.33.21"}]
      - ["forwarded_port", {guest: 80, host: 8008, auto_correct: true}]
      require_chef_omnibus: 11.12.4

suites:
  - name: mysql
    run_list:
      - recipe[yum-epel]
      - recipe[apache2::default]
      - recipe[mysql::server]
      - recipe[mysql::client]
      - recipe[mysql-custom::default]
      - recipe[zabbix]
      - recipe[zabbix::database]
      - recipe[zabbix::server]
      - recipe[zabbix::web]
      - recipe[zabbix-custom::japanese_font]
      - recipe[chef-serverspec-handler::default]
    attributes:
      zabbix:
        server:
          version: 2.2.1
        agent:
          servers: ['localhost']
          version: 2.2.1
        web:
          fqdn: 'localhost'
      mysql:
        server_root_password: nil

  - name: postgresql
    run_list:
      - recipe[yum-epel]
      - recipe[apache2::default]
      - recipe[postgresql::server]
      - recipe[postgresql::client]
      - recipe[zabbix]
      - recipe[zabbix::database]
      - recipe[zabbix::server]
      - recipe[zabbix::web]
      - recipe[zabbix-custom::japanese_font]
    attributes:
      zabbix:
        database:
          install_method: 'postgres'
        server:
          version: 2.2.1
        agent:
          servers: ['localhost']
          version: 2.2.1
        web:
          fqdn: 'localhost'
      postgresql:
        password:
          postgres: nil
