source "https://api.berkshelf.com"

group :production do
  cookbook 'zabbix', '0.8.0'
  cookbook 'zabbix-custom', git: 'https://github.com/ryoogata/zabbix-custom.git'
  cookbook 'mysql', '5.2.12'
  cookbook 'mysql-custom', git: 'https://github.com/ryoogata/mysql-custom.git'
  cookbook 'postgresql', '3.4.0'
  cookbook 'yum-epel', '0.3.6'
  cookbook 'yum', '3.2.0'
  cookbook 'apache2', '1.10.4'
  cookbook 'chef-serverspec-handler', path: '/Users/ryo/Dropbox/chef-repo/site-cookbooks/chef-serverspec-handler'
end

group :test do
  cookbook 'zabbix'
  cookbook 'zabbix-custom', git: 'https://github.com/ryoogata/zabbix-custom.git'
  cookbook 'mysql'
  cookbook 'mysql-custom', git: 'https://github.com/ryoogata/mysql-custom.git'
  cookbook 'postgresql'
  cookbook 'yum-epel'
  cookbook 'yum'
  cookbook 'apache2'
end

group :development do
  cookbook 'zabbix'
  cookbook 'zabbix-custom', git: 'https://github.com/ryoogata/zabbix-custom.git'
  cookbook 'mysql'
  cookbook 'mysql-custom', git: 'https://github.com/ryoogata/mysql-custom.git'
  cookbook 'postgresql'
  cookbook 'yum-epel'
  cookbook 'yum'
  cookbook 'apache2'
  cookbook 'chef-serverspec-handler', path: '/Users/ryo/Dropbox/chef-repo/site-cookbooks/chef-serverspec-handler'
end
