---
driver:
  name: vagrant
  driver_config:
    require_chef_omnibus: 11.12.4

provisioner:
  name: chef_solo
  environments_path: "test/integration/environments"
  data_bags_path: "test/integration/data_bags"

platforms:
  - name: ubuntu-13.10
    driver:
      box: opscode-ubuntu-13.10
    driver_config:
      network:
      - ["forwarded_port", {guest: 80, host: 8000}]
      - ["private_network", {ip: "192.168.33.10"}]

  - name: centos-6.5
    driver:
      box: opscode-centos-6.5
    driver_config:
      network:
      - ["forwarded_port", {guest: 80, host: 8080}]
      - ["private_network", {ip: "192.168.33.20"}]

suites:
  - name: default
    run_list:
    - recipe[apache2::default]
    attributes:
      apache:
        default_site_enabled: 'true'
