---
provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5
    driver:
      name: vagrant
    driver_config:
      require_chef_omnibus: 11.12.4
      network:
      - ["private_network", {ip: "192.168.33.40"}]
      - ["forwarded_port", {guest: 80, host: 8080}]

suites:
  - name: default
    run_list:
      - recipe[nginx::default]
      - recipe[nginx::ohai_plugin]
    attributes:
  - name: source
    run_list:
      - recipe[yum::default]
      - recipe[yum-epel::default]
      - recipe[nginx::source]
    attributes:
