---
provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5
    driver:
      name: vagrant
      driver_config:
        require_chef_omnibus: 11.12.4
    driver_config:
      network:
      - ["forwarded_port", {guest: 80, host: 8080}]
      - ["private_network", {ip: "192.168.33.1"}]

  - name: ec2-amazonlinux-2014031
    driver:
      name: ec2
      image_id: ami-c9562fc8
      username: ec2-user
      aws_access_key_id: 
      aws_secret_access_key: 
      flavor_id: "t1.micro"
      aws_ssh_key_id: 
      ssh_key: 
      security_group_ids: 
      region: ap-northeast-1
      availability_zone: ap-northeast-1a
      interface: public

suites:
  - name: default
    run_list:
      - recipe[wordpress::default]
    attributes:
      mysql:
        server_root_password: 'secretpassword'
        server_repl_password: 'secretpassword'
        server_debian_password: 'secretpassword'
      wordpress:
        server_name: 'localhost'
