---
provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5
    driver:
      name: vagrant
      driver_config:
        require_chef_omnibus: 11.12.4
    driver_config:
      network:
      - ["private_network", {ip: "192.168.33.12"}]
      - ["forwarded_port", {guest: 80, host: 8002, auto_correct: true}]

suites:
  - name: default
    run_list:
      - recipe[wordpress::default]
      - recipe[wordpress::languages]
    attributes:
      mysql:
        server_root_password: 'secretpassword'
      wordpress:
        server_name: 'localhost'
