---
driver:
  name: vagrant
  driver_config:
    require_chef_omnibus: 11.12.4

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5
    driver_config:
      network:
      - ["forwarded_port", {guest: 8080, host: 8080}]
      - ["private_network", {ip: "192.168.33.1"}]

suites:
  - name: default
    run_list:
      - recipe[jenkins::java]
      - recipe[jenkins::master]
    attributes:
      jenkins:
        master:
          port: '8080'
