source "https://api.berkshelf.com"

group :production do
  cookbook 'jenkins', '2.0.2'
  cookbook 'yum', '3.2.0'
  cookbook 'yum-epel', '0.3.6'
  cookbook 'apt', '2.4.0'
  cookbook 'build-essential', '2.0.2'
  cookbook 'runit', '1.5.10'
end

group :test do
  cookbook 'jenkins'
  cookbook 'yum'
  cookbook 'yum-epel'
  cookbook 'apt'
  cookbook 'build-essential'
  cookbook 'runit'
end

group :development do
  cookbook 'jenkins'
  cookbook 'yum'
  cookbook 'yum-epel'
  cookbook 'apt'
  cookbook 'build-essential'
  cookbook 'runit'
  cookbook 'chef-serverspec-handler', path: '/Users/ryo/Dropbox/chef-repo/site-cookbooks/chef-serverspec-handler'
end
