source "https://api.berkshelf.com"

cookbook 'jenkins', '2.0.2'
cookbook 'yum', '3.2.0'
cookbook 'yum-epel', '0.3.6'
cookbook 'apt', '2.4.0'
cookbook 'build-essential', '2.0.2'
cookbook 'runit', '1.5.10'
