---
driver:
  name: vagrant
  driver_config:
    require_chef_omnibus: 11.12.4

provisioner:
  name: chef_solo
  environments_path: "test/integration/environments"
  data_bags_path: "test/integration/data_bags"

platforms:
  - name: centos-6.5
    driver:
      box: opscode-centos-6.5
    driver_config:
      network:
      - ["private_network", {ip: "192.168.33.22"}]
      - ["forwarded_port", {guest: 80, host: 8009, auto_correct: true}]

  - name: ubuntu-13.10
    driver:
      box: opscode-ubuntu-13.10
    driver_config:
      network:
      - ["private_network", {ip: "192.168.33.23"}]
      - ["forwarded_port", {guest: 80, host: 8010, auto_correct: true}]

suites:
  - name: default
    run_list:
      - recipe[git::source]
      - recipe[apache2::default]
      - recipe[mysql::server]
      - recipe[mysql-custom::default]
      - recipe[database::mysql]
      - recipe[php::default]
      - recipe[php::package]
      - recipe[php::module_gd]
      - recipe[php::module_ldap]
      - recipe[php::module_mysql]
      - recipe[limesurvey::default]
    attributes:
      mysql:
        server_root_password: 'secretpassword'
      git:
        version: '1.9.4'
      apache:
        default_site_enabled: 'true'
