---
provisioner:
  name: chef_solo
  environments_path: test/integration/environments
  solo_rb:
    environment: development

platforms:
  - name: centos-6.5
    driver:
      name: vagrant
    driver_config:
      require_chef_omnibus: 11.12.4
      network:
      - ["private_network", {ip: "192.168.33.16"}]

  - name: ubuntu-14.04
    driver:
      name: vagrant
    driver_config:
      require_chef_omnibus: 11.12.4
      network:
      - ["private_network", {ip: "192.168.33.17"}]


suites:
  - name: default
    run_list:
      - recipe[mysql::server]
    attributes:
      mysql:
        server_root_password: 'secretpassword'
