---
provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    driver:
      name: vagrant
    driver_config:
      require_chef_omnibus: 11.12.4
      network:
      - ["private_network", {ip: "192.168.33.30"}]

  - name: centos-6.5
    driver:
      name: vagrant
    driver_config:
      require_chef_omnibus: 11.12.4
      network:
      - ["forwarded_port", {guest: 80, host: 8080}]
      - ["private_network", {ip: "192.168.33.1"}]

suites:
  - name: default
    run_list:
      - recipe[mysql::server]
      - recipe[mysql-custom::default]
    attributes:
      mysql:
        server_root_password: 'secretpassword'
        server_repl_password: 'secretpassword'
        server_debian_password: 'secretpassword'
