source "https://api.berkshelf.com"

group :production do
  cookbook 'mysql', '5.2.12'
end

group :test do
  cookbook 'mysql'
end

group :development do
  cookbook 'mysql'
  cookbook 'mysql-custom', path: '/Users/ryo/Dropbox/chef-repo/site-cookbooks/mysql-custom'
end
