---
driver:
  name: vagrant
  driver_config:
    require_chef_omnibus: 11.12.4

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5
    driver_config:
      network:
      - ["private_network", {ip: "192.168.33.24"}]
      - ["forwarded_port", {guest: 80, host: 8011, auto_correct: true}]

suites:
  - name: default
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[yum::default]
      - recipe[yum-epel::default]
      - recipe[munin::server]
    attributes:
      fqdn: 'localhost'
      munin:
        server_auth_method: 'htauth'
