source "https://api.berkshelf.com"

cookbook 'munin', '1.4.3'
cookbook 'apache2', '1.10.4'
cookbook 'apt', '2.4.0'
cookbook 'iptables', '0.13.2'
cookbook 'logrotate', '1.5.0'
cookbook 'pacman', '1.1.1'
cookbook 'yum', '3.2.0'
cookbook 'yum-epel', '0.3.6'
cookbook 'build-essential', '2.0.2'
cookbook 'ohai', '2.0.0'
cookbook 'rsyslog', '1.12.2'
cookbook 'runit', '1.5.10'
