source "https://api.berkshelf.com"

cookbook 'eccube', git: "https://github.com/ryoogata/eccube.git"
cookbook 'mysql', '5.2.12'
cookbook 'apache2', '1.10.4'
cookbook 'database', '2.2.0'
cookbook 'php', '1.4.6'
